### ISSUE TITLE
Compile Test taking 6-15 seconds per composite resource

### ISSUE THREAD

**Issue by dan-hughes** [raandree/DscConfig.M365#23]
### Problem description

The compile test for each composite takes longer than it should.

### Verbose logs

```text
'cAADApplication' compiles 16.05s (16.05s|3ms)
```

### How to reproduce

Run build.ps1

### Expected behavior

Composite to compile in something similar to the native M365 resource 1-3 seconds.

### Current behavior

It takes more than 10 seconds to test the compile step.

### Suggested solution

N/A

### Operating system the target node is running

```text
OsName               : Microsoft Windows 11 Business
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-GB
OsMuiLanguages       : {en-GB, en-US}
```

### PowerShell version and build the target node is running

```text
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module version used

```text
0.3.1
```

**Comment by dan-hughes** [comment]
@raandree Is there any logging I can turn on to find out why it's taking so long to compile?

**Comment by raandree** [comment]
I see the same behaviour locally and in the pipeline. So far it hasn't bothered me as the build of this module is only executed very rarely.

I haven't implemented any meaningful logging yet. The [Profiler](https://github.com/nohwnd/Profiler) might come in handy to detect the delay.

**Comment by dan-hughes** [comment]
I was adding some Teams composites and having to run the 70+ tests could be better.

I wonder if Profiler will output from inside a test?

**Comment by dan-hughes** [comment]
@raandree, created PR to make it much faster.

**Comment by raandree** [comment]
Thank you, @dan-hughes. That was a simple and very effective fix.

Can we expect another PR for the Teams configurations you mentioned?

**Comment by dan-hughes** [comment]
Yes, a few things to investigate first. e.g. [TeamsClientConfiguration](https://microsoft365dsc.com/resources/teams/TeamsClientConfiguration/) requires a `Identity = 'Global'` to be passed but I'm unsure if it's a scalar or array to begin with. 

It's also 58 resources which is why this issue was a little painful!
